### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fireflysemantics** [alexindigo/install-peers#3]
Hi,
I'm trying it out on this project:

https://github.com/fireflysemantics/slice

I ran the install and see `    "install-peers": "^1.0.3",
` in my dev dependencies.  I run `npm i` and this is the result:

```
ole@mkt:~/Github/slice$ npm i
npm WARN @fireflysemantics/slice@9.0.4 requires a peer of rxjs@^6.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 879131 packages in 5s
found 0 vulnerabilities
```

It still skips installing the RxJS peer dependency.  Thoughts?

**Comment by alexindigo** [comment]
What's your npm version? And nodejs version as well?

**Comment by ayan4m1** [comment]
Closing as this issue has not received an update in over two years.
